# Generated by Django 4.2.2 on 2024-08-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("description", "0002_delete_doctors"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="description_media/image", verbose_name="Картинка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание",
                "verbose_name_plural": "Описания",
                "ordering": ("heading",),
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("lastname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Отчество (если есть)",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=250, verbose_name="Специализация"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="description_media/photo",
                        verbose_name="Фотография",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ("lastname",),
            },
        ),
    ]
