# Generated by Django 4.2.2 on 2024-08-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("description", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companydescription",
            options={
                "ordering": ("heading",),
                "permissions": [
                    ("can_edit_heading", "Может менять заголовок"),
                    ("can_edit_description", "Может менять описание"),
                    ("can_edit_image", "Может менять картинку"),
                ],
                "verbose_name": "Описание",
                "verbose_name_plural": "Описания",
            },
        ),
        migrations.AlterModelOptions(
            name="doctors",
            options={
                "ordering": ("lastname",),
                "permissions": [
                    ("can_edit_specialization", "Может менять специализацию"),
                    ("can_edit_photo", "Может менять фото"),
                    ("can_edit_description", "Может менять описание"),
                ],
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
    ]
