# Generated by Django 4.2.2 on 2024-08-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("description", "0004_alter_companydescription_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companydescription",
            options={
                "permissions": [
                    ("can_edit_heading", "Может менять заголовок"),
                    ("can_edit_description", "Может менять описание"),
                    ("can_edit_image", "Может менять картинку"),
                ],
                "verbose_name": "Описание",
                "verbose_name_plural": "Описания",
            },
        ),
    ]
