# Generated by Django 4.2.2 on 2024-08-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("description", "0005_alter_companydescription_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompanyDescription",
            new_name="Company",
        ),
    ]
