# Generated by Django 5.1 on 2024-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
