# Generated by Django 5.1 on 2024-08-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={
                "ordering": ["service", "price"],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("patronymic", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                ("specialization", models.CharField(max_length=250)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="description_media/photo"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Услуга",
                        to="catalog.services",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ("lastname",),
            },
        ),
    ]
