# Generated by Django 5.1 on 2024-08-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_services_options_doctors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={
                "ordering": ["service_name", "price"],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.RenameField(
            model_name="services",
            old_name="service",
            new_name="service_name",
        ),
    ]
