# Generated by Django 5.1 on 2024-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_services_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="lastname",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="patronymic",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Отчество (если есть)",
            ),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="description_media/photo",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="specialization",
            field=models.CharField(max_length=250, verbose_name="Специализация"),
        ),
    ]
