# Generated by Django 4.2.2 on 2024-08-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_doctors_lastname_alter_doctors_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctors",
        ),
    ]
