# Generated by Django 4.2.2 on 2024-08-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_delete_doctors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={
                "ordering": ["service_name", "price"],
                "permissions": [
                    ("can_edit_price", "Может менять цену"),
                    ("can_edit_description", "Может менять описание"),
                ],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
