# Generated by Django 4.2.2 on 2024-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_services_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_title",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Текст",
                "verbose_name_plural": "Тексты",
                "permissions": [
                    ("can_edit_description_title", "Может менять заголовок"),
                    ("can_edit_description", "Может менять описание"),
                ],
            },
        ),
    ]
