# Generated by Django 4.2.2 on 2024-08-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.services",
                        verbose_name="Название услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга из каталога",
                "verbose_name_plural": "Услуги из каталога",
            },
        ),
    ]
