# Generated by Django 4.2.2 on 2024-08-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_servicescatalog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServicesCatalog",
        ),
    ]
